// templates/react/src/components/ConnectionStatus.tsx
import { useConnectionStatus } from '@triplit/react';
import { triplit } from '../../triplit/client.ts';

export function ConnectionStatus() {
  const status = useConnectionStatus(triplit);
  return (
    <div className="connection-status">
      <div className={`indicator ${status.toLowerCase()}`}></div>
      {status === 'CLOSED'
        ? 'Offline'
        : status === 'CONNECTING'
        ? 'Connecting'
        : 'Online'}
    </div>
  );
}

// templates/vue/src/components/ConnectionStatus.vue
<script setup lang="ts">
import { useConnectionStatus } from '@triplit/vue'
import { triplit } from '@/lib/client'

const { connectionStatus } = useConnectionStatus(triplit)
</script>

<template>
  <div class="connection-status">
    <div :class="`indicator ${connectionStatus.toLowerCase()}`"></div>
    {{
      connectionStatus === 'CLOSED'
        ? 'Offline'
        : connectionStatus === 'CONNECTING'
        ? 'Connecting'
        : 'Online'
    }}
  </div>
</template>
