// templates/angular/src/app/connection-status/connection-status.component.ts
import { Component } from '@angular/core';
import { injectConnectionStatus } from '@triplit/angular';
import { triplit } from '../../../triplit/client.js';

@Component({
  selector: 'app-connection-status',
  standalone: true,
  template: ` <div class="connection-status">
    <div class="{{ 'indicator ' + status().toLowerCase() }}"></div>
    @if (status() === 'CLOSED') {Offline} @else if (status() === 'CONNECTING')
    {Connecting} @else {Online}
  </div>`,
})
export class ConnectionStatusComponent {
  status = injectConnectionStatus(triplit);
}

// templates/react/src/components/ConnectionStatus.tsx
import { useConnectionStatus } from '@triplit/react';
import { triplit } from '../../triplit/client.ts';

export function ConnectionStatus() {
  const status = useConnectionStatus(triplit);
  return (
    <div className="connection-status">
      <div className={`indicator ${status.toLowerCase()}`}></div>
      {status === 'CLOSED'
        ? 'Offline'
        : status === 'CONNECTING'
        ? 'Connecting'
        : 'Online'}
    </div>
  );
}
