// templates/vue/src/components/Todo.vue
<script setup lang="ts">
import { triplit } from '../lib/client'

const props = defineProps<{ id: string; completed: boolean; text: string }>()

function toggleStatus(id: string) {
  triplit.update('todos', id, (todo) => {
    todo.completed = !todo.completed
  })
}

function deleteTodo(id: string) {
  triplit.delete('todos', id)
}
</script>

<template>
  <div class="todo">
    <input @click="toggleStatus(props.id)" type="checkbox" :checked="props.completed" />
    {{ props.text }}
    <button class="x-button" @click="deleteTodo(props.id)">❌</button>
  </div>
</template>

// templates/react/src/components/Todo.tsx
import { Entity } from '@triplit/client';
import { schema } from '../../triplit/schema';
import { triplit } from '../../triplit/client';

type Todo = Entity<typeof schema, 'todos'>;

export default function Todo({ todo }: { todo: Todo }) {
	return (
		<div className="todo">
			<input
				type="checkbox"
				checked={todo.completed}
				onChange={() =>
					triplit.update('todos', todo.id, async (entity) => {
						entity.completed = !todo.completed;
					})
				}
			/>
			{todo.text}
			<button
				className="x-button"
				onClick={() => {
					triplit.delete('todos', todo.id);
				}}
			>
				❌
			</button>
		</div>
	);
}
